# Generated by Django 3.2 on 2021-05-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_repository'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
    ]
